# Generated by Django 5.2 on 2025-04-25 23:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(
                    choices=[('clothing', 'Одежда'), ('electronics', 'Электроника'), ('books', 'Книги'),
                             ('furniture', 'Мебель'), ('toys', 'Игрушки'), ('other', 'Другое')], default='other',
                    max_length=30)),
                ('condition',
                 models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], default='used', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('status',
                 models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')],
                                  default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals',
                                   to='ads.ad')),
                ('ad_sender',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals',
                                   to='ads.ad')),
            ],
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category'], name='ads_ad_categor_aafbda_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['condition'], name='ads_ad_conditi_1d704d_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ads_ad_search__865551_gin'),
        ),
        migrations.AddIndex(
            model_name='exchangeproposal',
            index=models.Index(fields=['status'], name='ads_exchang_status_de2e30_idx'),
        ),
    ]
